name: Rust

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --no-default-features --features mysql --verbose
    - name: Run tests with mysql features
      run: cargo test --no-default-features --features mysql --verbose
    - name: Run tests with postgresql features
      run: cargo test --no-default-features --features postgresql --verbose
    - name: Run tests with mssql features
      run: cargo test --no-default-features --features mssql --verbose
    - name: Run tests with sqlite features
      run: cargo test --no-default-features --features sqlite --verbose